-- Seed data for CineSphere Supabase project
-- Insert a default admin user and sample films matching `dummyFilms.ts`

-- Insert movies that mirror dummyFilms.ts
INSERT INTO public.movies (
  title, description, youtube_url, youtube_video_id, thumbnail_url,
  category, genre, year, duration, country, language, director, director_bio,
  cinematographer, characteristics, cast_members, awards, is_featured, status, uploaded_by, created_at
) VALUES
(
  'Sanctuary',
  'A wealthy heir attempts to sever ties with his dominatrix in this audacious two-hander. What unfolds is a battle of wits that reveals deeper truths about power dynamics and human connection.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&h=800',
  'Drama',
  NULL,
  2022,
  '1h 36min',
  'United States',
  'English',
  'Zach Wigon',
  'Zach Wigon is an American filmmaker known for his sharp, character-driven narratives. His work often explores power dynamics and psychological complexity, earning him recognition at major film festivals. Sanctuary marks his breakthrough feature, praised for its bold storytelling.',
  'Ludovica Isidori',
  ARRAY['PSYCHOLOGICAL','DRAMA','INTIMATE','PROVOCATIVE'],
  ARRAY['Margaret Qualley','Christopher Abbott'],
  ARRAY['Sundance Film Festival - Official Selection','SXSW - Audience Award Nominee'],
  TRUE,
  'approved',
  NULL,
  now() - interval '5 days'
),
(
  'Limonov',
  'The ballad of Eduard Limonov, the radical Soviet poet who became an infamous political figure. A sweeping epic of rebellion, art, and the search for identity across decades.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&h=800',
  'Biography',
  NULL,
  2024,
  '2h 18min',
  'France / Italy',
  'English / Russian',
  'Kirill Serebrennikov',
  'Kirill Serebrennikov is a visionary Russian director and theater artist, known for his daring and politically charged work. Despite facing persecution in Russia, he continues to create provocative films that challenge convention.',
  'Roman Vasyanov',
  ARRAY['BIOGRAPHY','EPIC','POLITICAL','ARTISTIC'],
  ARRAY['Ben Whishaw','Viktoria Miroshnichenko'],
  ARRAY['Cannes Film Festival - In Competition','European Film Award Nominee'],
  TRUE,
  'approved',
  NULL,
  now() - interval '4 days'
),
(
  'Scarlet',
  'A wounded WWI veteran returns to Normandy to raise his daughter alone. Years later, she dreams of a prince who will come for her on a ship with scarlet sails.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=1200&h=800',
  'Romance',
  NULL,
  2022,
  '1h 44min',
  'France / Italy',
  'French',
  'Pietro Marcello',
  'Pietro Marcello is an Italian filmmaker celebrated for his lyrical storytelling and blend of documentary and fiction. His films often evoke a dreamlike quality, merging past and present in poetic ways.',
  'Marco Graziaplena',
  ARRAY['ROMANTIC','FAIRY TALE','POST-WAR','POETIC'],
  ARRAY['Raphaël Thiéry','Juliette Jouan'],
  ARRAY['Cannes Film Festival - Un Certain Regard','David di Donatello Award'],
  FALSE,
  'approved',
  NULL,
  now() - interval '3 days'
),
(
  'The World To Come',
  'In the harsh farmlands of 19th century America, two women forge an unexpected connection that defies the constraints of their time and circumstance.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=1200&h=800',
  'Drama',
  NULL,
  2020,
  '1h 45min',
  'United States',
  'English',
  'Mona Fastvold',
  'Mona Fastvold is a Norwegian filmmaker and screenwriter known for her atmospheric period pieces. Her work often explores forbidden desires and the inner lives of women constrained by society.',
  'André Chemetoff',
  ARRAY['PERIOD','RELATIONSHIPS','INTIMATE','LYRICAL'],
  ARRAY['Katherine Waterston','Vanessa Kirby','Casey Affleck'],
  ARRAY['Venice Film Festival - Queer Lion','Berlin Film Festival Nominee'],
  FALSE,
  'approved',
  NULL,
  now() - interval '12 days'
),
(
  'Persian Lessons',
  'A Jewish man survives a concentration camp by pretending to be Persian. When a Nazi officer demands lessons, he must invent an entire language to stay alive.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=1200&h=800',
  'War',
  NULL,
  2020,
  '2h 7min',
  'Germany / Russia',
  'German / Farsi',
  'Vadim Perelman',
  'Vadim Perelman is a Ukrainian-American filmmaker known for intense dramas that explore survival and human resilience. His films often deal with historical tragedies through deeply personal narratives.',
  'Vladislav Opelyants',
  ARRAY['SURVIVAL','WAR','THRILLER','HISTORICAL'],
  ARRAY['Nahuel Pérez Biscayart','Lars Eidinger'],
  ARRAY['German Film Award - Best Picture Nominee','Jerusalem Film Festival - Best Actor'],
  FALSE,
  'approved',
  NULL,
  now() - interval '15 days'
),
(
  'Docu-style',
  'Documentary-style shooting has experienced a significant surge in popularity. This ad style resonates because it reflects life as it is: honest, emotional, and deeply human.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1544531586-fde5298cdd40?w=1200&h=800',
  'Documentary',
  NULL,
  2026,
  '45min',
  'Canada',
  'English / Japanese',
  'Goh Iromoto',
  'Goh Iromoto is a Canadian-Japanese documentary filmmaker known for authentic, emotionally resonant storytelling. His work captures intimate human moments with an unobtrusive, naturalistic approach.',
  'Goh Iromoto',
  ARRAY['PORTRAITS','HANDHELD','RELATIONSHIPS','DOCUMENTARY'],
  ARRAY['Documentary subjects'],
  ARRAY['Hot Docs - World Premiere','IDFA - Special Mention'],
  FALSE,
  'pending',
  NULL,
  now() - interval '1 hour'
),
(
  'Aftersun',
  'Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between as she tries to reconcile the father he knew with the man he did not.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=800',
  'Drama',
  NULL,
  2022,
  '1h 41min',
  'United Kingdom / United States',
  'English',
  'Charlotte Wells',
  'Charlotte Wells is a Scottish filmmaker whose debut feature Aftersun earned widespread critical acclaim. Her work is characterized by its tender exploration of memory, grief, and the complexity of parent-child relationships.',
  'Gregory Oke',
  ARRAY['MEMORY','FATHER-DAUGHTER','NOSTALGIC','MELANCHOLIC'],
  ARRAY['Paul Mescal','Frankie Corio'],
  ARRAY['Cannes Film Festival - Critics'' Week Grand Prize','BAFTA - Outstanding British Film','Independent Spirit Award - Best First Feature'],
  FALSE,
  'approved',
  NULL,
  now() - interval '2 days'
),
(
  'Past Lives',
  'Two childhood friends reunite after decades apart, navigating the space between what might have been and what is.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=800',
  'Romance',
  NULL,
  2023,
  '1h 46min',
  'United States / South Korea',
  'English / Korean',
  'Celine Song',
  'Celine Song is a Korean-Canadian playwright and filmmaker. Her debut feature Past Lives draws from her own experiences of immigration and explores themes of fate, identity, and the paths not taken.',
  'Shabier Kirchner',
  ARRAY['ROMANCE','FATE','CONNECTION','BITTERSWEET'],
  ARRAY['Greta Lee','Teo Yoo','John Magaro'],
  ARRAY['Sundance Film Festival - Premiere','Golden Globe Nominee','Academy Award Nominee - Best Picture'],
  FALSE,
  'approved',
  NULL,
  now() - interval '3 days'
),
(
  'All of Us Strangers',
  'A screenwriter draws close to a mysterious neighbor while also reconnecting with his parents, who died thirty years ago.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=800',
  'Fantasy',
  NULL,
  2023,
  '1h 45min',
  'United Kingdom',
  'English',
  'Andrew Haigh',
  'Andrew Haigh is a British filmmaker celebrated for his intimate character studies. Known for films like Weekend and 45 Years, his work delves into loneliness, desire, and the search for connection.',
  'Jamie D. Ramsay',
  ARRAY['SUPERNATURAL','GRIEF','LOVE','HAUNTING'],
  ARRAY['Andrew Scott','Paul Mescal','Jamie Bell','Claire Foy'],
  ARRAY['BFI London Film Festival - Opening Night','BAFTA Nominee','Critics Choice Award Nominee'],
  FALSE,
  'approved',
  NULL,
  now() - interval '4 days'
),
(
  'Anatomy of a Fall',
  'A woman is suspected of her husband''s murder, and their blind son faces a moral dilemma as the key witness.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=800',
  'Thriller',
  NULL,
  2023,
  '2h 32min',
  'France',
  'French / English / German',
  'Justine Triet',
  'Justine Triet is a French filmmaker known for her incisive character studies and complex narratives. Anatomy of a Fall won the Palme d''Or, establishing her as one of contemporary cinema''s most vital voices.',
  'Simon Beaufils',
  ARRAY['COURTROOM','MYSTERY','PSYCHOLOGICAL','INTENSE'],
  ARRAY['Sandra Hüller','Swann Arlaud','Milo Machado-Graner'],
  ARRAY['Cannes Film Festival - Palme d''Or','Academy Award - Best Original Screenplay','Golden Globe - Best Foreign Language Film'],
  FALSE,
  'approved',
  NULL,
  now() - interval '5 days'
),
(
  'The Zone of Interest',
  'The commandant of Auschwitz and his wife strive to build a dream life for their family in a house and garden next to the camp.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=800',
  'Drama',
  NULL,
  2023,
  '1h 45min',
  'United Kingdom / Poland',
  'German / Polish',
  'Jonathan Glazer',
  'Jonathan Glazer is a British filmmaker and music video director known for his visually stunning and thematically daring work. His films, including Sexy Beast and Under the Skin, are marked by their unique formal approach.',
  'Łukasz Żal',
  ARRAY['HISTORICAL','HORROR','ARTISTIC','DISTURBING'],
  ARRAY['Christian Friedel','Sandra Hüller'],
  ARRAY['Cannes Film Festival - Grand Prix','Academy Award - Best International Feature','BAFTA - Best British Film'],
  FALSE,
  'approved',
  NULL,
  now() - interval '6 days'
),
(
  'Poor Things',
  'The incredible tale of Bella Baxter, a young woman brought back to life by an eccentric scientist, who runs off with a lawyer on a whirlwind adventure across the continents.',
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  NULL,
  'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=1200&h=800',
  'Comedy',
  NULL,
  2023,
  '2h 21min',
  'United Kingdom / Ireland / United States',
  'English',
  'Yorgos Lanthimos',
  'Yorgos Lanthimos is a Greek filmmaker known for his darkly absurdist style. From The Lobster to The Favourite, his films explore societal norms through surreal, often unsettling narratives.',
  'Robbie Ryan',
  ARRAY['SURREAL','FEMINIST','DARK COMEDY','VISUAL'],
  ARRAY['Emma Stone','Mark Ruffalo','Willem Dafoe'],
  ARRAY['Venice Film Festival - Golden Lion','Academy Award - Best Actress','Golden Globe - Best Motion Picture Musical/Comedy'],
  FALSE,
  'approved',
  NULL,
  now() - interval '7 days'
);
